# Generated by Django 4.2.29 on 2026-04-10 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_restaurant_created_by_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewreply',
            options={'verbose_name_plural': 'Review Replies'},
        ),
        migrations.AlterField(
            model_name='restaurantphoto',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
